apiVersion: v1
kind: Service
metadata:
  name: python-web-app-lb
  labels:
    app: python-web-app
spec:
  type: LoadBalancer
  selector:
    app: python-web-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
